version: "3.9"

services:
  cypress:
    container_name: cypress-xquartz
    environment:
      - XAUTHORITY=/.Xauthority
    volumes:
      # for Cypress to communicate with the X11 server pass this socket file
      # in addition to any other mapped volumes
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority:rw
