# Using docker multi stage builds for layer caching
FROM node:12.21 AS base

WORKDIR /usr/src/app

# build step
FROM base AS build

COPY package.json .
COPY yarn.lock .

COPY packages/api/package.json ./packages/api/
COPY packages/web/package.json ./packages/web/

# install gatsby-cli globally in the web folder
WORKDIR /usr/src/app/packages/web

RUN yarn global add gatsby-cli
RUN gatsby telemetry --disable

# move back to the root folder for yarn hoisting
WORKDIR /usr/src/app

# --pure-lockfile: don't recreate a lock file
RUN yarn install --production --pure-lockfile

# Install all dependencies
RUN yarn install --pure-lockfile

# Copy packages source files
COPY packages/api/ ./packages/api/
COPY packages/web/ ./packages/web/

# web
# assign a specific port for the gatsby ws connection
ENV INTERNAL_STATUS_PORT=45720
EXPOSE 8000 45720

# api
EXPOSE 4000

FROM cypress/included:6.5.0

WORKDIR /usr/src/app
COPY --from=build /usr/src/app .

WORKDIR /usr/src/app/e2e

COPY --from=build /usr/src/app/packages/web/node_modules/ ./node_modules
COPY --from=build /usr/src/app/packages/web/cypress/ ./cypress
COPY --from=build /usr/src/app/packages/web/cypress.json .
