version: "3.9"

services:
  mongo:
    container_name: mongo
    image: mongo:4.4.15
    restart: unless-stopped
    ports:
      - "27017:27017"
      - "27018:27017"
    volumes:
      - mongo_data_vol:/data/mongodb
    env_file:
      - ./packages/api/.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    env_file:
      - ./packages/api/.env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}

volumes:
  mongo_data_vol:
