version: "3.9"

services:
  cypress:
    container_name: cypress
    # pass custom command to start Cypress otherwise it will use the entrypoint
    # specified in the Cypress Docker image.
    # also pass "--project <folder>" so that when Cypress opens
    # it can find file "cypress.json" and show integration specs
    # https://on.cypress.io/command-line#cypress-open
    command: cypress open --env configFile=dev
    depends_on:
      - web
    build:
      context: ./packages/web
      dockerfile: Dockerfile.cypress
    environment:
      # pass base url to test pointing at the web application
      # must be the same as the gatsby url
      - CYPRESS_baseUrl=http://172.25.0.101:8000
    volumes:
      - ./packages/web:/usr/src/e2e
      - e2e:/usr/src/e2e/node_modules
    networks:
      web_net:

volumes:
  e2e:
