name: Dev CI Workflow

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  check-skip-run:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

  install:
    needs: check-skip-run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: node_modules cache
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: |
            **/node_modules
          key: npm-${{ hashFiles('**/yarn-lock.json') }}
      - name: install yarn globally
        run: npm install -g yarn
      - name: install yarn dependencies
        run: yarn

  lint:
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: node_modules cache
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: |
            **/node_modules
          key: npm-${{ hashFiles('**/yarn-lock.json') }}
      - name: api lint
        run: |
          yarn workspace api run lint:js
          yarn workspace api run lint:format:check
        env:
          FB_CERT_TYPE: ${{ secrets.FB_CERT_TYPE }}
          FB_CERT_PROJECT_ID: ${{ secrets.FB_CERT_PROJECT_ID }}
          FB_CERT_PRIVATE_KEY_ID: ${{ secrets.FB_CERT_PRIVATE_KEY_ID }}
          FB_CERT_PRIVATE_KEY: ${{ secrets.FB_CERT_PRIVATE_KEY }}
          FB_CERT_CLIENT_EMAIL: ${{ secrets.FB_CERT_CLIENT_EMAIL }}
          FB_CERT_CLIENT_ID: ${{ secrets.FB_CERT_CLIENT_ID }}
          FB_CERT_AUTH_URI: ${{ secrets.FB_CERT_AUTH_URI }}
          FB_CERT_TOKEN_URI: ${{ secrets.FB_CERT_TOKEN_URI }}
          FB_CERT_AUTH_PROVIDER_X_509_CERT_URL: ${{ secrets.FB_CERT_AUTH_PROVIDER_X_509_CERT_URL }}
          FB_CERT_CLIENT_X_509_CERT_URL: ${{ secrets.FB_CERT_CLIENT_X_509_CERT_URL }}
          MONGO_PROJECT_ID: ${{ secrets.MONGO_PROJECT_ID }}
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          CLIENT_URL: ${{ secrets.CLIENT_URL }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      - name: web lint
        run: |
          yarn workspace web run lint:js
          yarn workspace web run lint:format:check

  test:
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: node_modules cache
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: |
            **/node_modules
          key: npm-${{ hashFiles('**/yarn-lock.json') }}
      - name: api test
        run: yarn workspace api run test:ci:all
        env:
          FB_CERT_TYPE: ${{ secrets.FB_CERT_TYPE }}
          FB_CERT_PROJECT_ID: ${{ secrets.FB_CERT_PROJECT_ID }}
          FB_CERT_PRIVATE_KEY_ID: ${{ secrets.FB_CERT_PRIVATE_KEY_ID }}
          FB_CERT_PRIVATE_KEY: ${{ secrets.FB_CERT_PRIVATE_KEY }}
          FB_CERT_CLIENT_EMAIL: ${{ secrets.FB_CERT_CLIENT_EMAIL }}
          FB_CERT_CLIENT_ID: ${{ secrets.FB_CERT_CLIENT_ID }}
          FB_CERT_AUTH_URI: ${{ secrets.FB_CERT_AUTH_URI }}
          FB_CERT_TOKEN_URI: ${{ secrets.FB_CERT_TOKEN_URI }}
          FB_CERT_AUTH_PROVIDER_X_509_CERT_URL: ${{ secrets.FB_CERT_AUTH_PROVIDER_X_509_CERT_URL }}
          FB_CERT_CLIENT_X_509_CERT_URL: ${{ secrets.FB_CERT_CLIENT_X_509_CERT_URL }}
          MONGO_PROJECT_ID: ${{ secrets.MONGO_PROJECT_ID }}
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          CLIENT_URL: ${{ secrets.CLIENT_URL }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      - name: web test
        run: yarn workspace web run test:ci:all
