name: Prod CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci-prod-job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - name: api lint, format, test
        run: |
          yarn
          yarn workspace api run lint:js
          yarn workspace api run lint:format:check
          yarn workspace api run test:ci:all
        env:
          FB_CERT_TYPE: ${{ secrets.FB_CERT_TYPE }}
          FB_CERT_PROJECT_ID: ${{ secrets.FB_CERT_PROJECT_ID }}
          FB_CERT_PRIVATE_KEY_ID: ${{ secrets.FB_CERT_PRIVATE_KEY_ID }}
          FB_CERT_PRIVATE_KEY: ${{ secrets.FB_CERT_PRIVATE_KEY }}
          FB_CERT_CLIENT_EMAIL: ${{ secrets.FB_CERT_CLIENT_EMAIL }}
          FB_CERT_CLIENT_ID: ${{ secrets.FB_CERT_CLIENT_ID }}
          FB_CERT_AUTH_URI: ${{ secrets.FB_CERT_AUTH_URI }}
          FB_CERT_TOKEN_URI: ${{ secrets.FB_CERT_TOKEN_URI }}
          FB_CERT_AUTH_PROVIDER_X_509_CERT_URL: ${{ secrets.FB_CERT_AUTH_PROVIDER_X_509_CERT_URL }}
          FB_CERT_CLIENT_X_509_CERT_URL: ${{ secrets.FB_CERT_CLIENT_X_509_CERT_URL }}
          MONGO_PROJECT_ID: ${{ secrets.MONGO_PROJECT_ID }}
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          CLIENT_URL: ${{ secrets.CLIENT_URL }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      - name: web lint, format, test
        run: |
          yarn
          yarn workspace web run lint:js
          yarn workspace web run lint:format:check
          yarn workspace web run test:ci:all
      - name: Add Heroku Remote Origin
        run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_TOKEN
          }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
      - name: Split the packages/api subtree
        run: git subtree split --prefix packages/api -b split
      - name: Deploy API to Heroku
        run: git push -f heroku split:main
