name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]

jobs:
  firebase-functions:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: use node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: lint:js firebase functions
        working-directory: /functions
        run: |
          npm ci
          npm run lint:js

  project:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: use node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: lint | format | test project
        run: |
          npm ci
          npm run lint:js
          npm run lint:format:check
          npm run test:ci:all
