name: Node.js CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: use node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: lint | format | test project
        run: |
          npm ci
          npm run lint:js
          npm run lint:format:check
          npm run test:ci:all
      - name: lint:js firebase functions with node.10
        working-directory: /functions
        uses: actions/setup-node@v2
        with:
          node-version: "10"
        run: |
          npm ci
          npm run lint:js
