name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Setup Contact Firebase Function with Node.js 10
        working-directory: /functions
        with:
          node-version: "10"
        run: |
          npm ci
          npm run lint:js
      - name:
          Test & Lint the Entire Project with Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, lint, and test
        run: |
          npm ci
          npm run lint:js
          npm run lint:format:check
          npm run test:ci:all
